# Generated by Django 5.1.4 on 2025-01-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicalsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicaldata",
            name="componentName",
            field=models.CharField(
                choices=[
                    ("hw", "Height/Weight"),
                    ("bp", "Blood Pressue"),
                    ("heartrate", "Heart Rate"),
                ],
                max_length=20,
            ),
        ),
    ]
